#!/usr/bin/env python

from . import user

VirtualKeys = {'LBUTTON': 0x01,
                'RBUTTON': 0x02,
                'CANCEL': 0x03,
                'MBUTTON': 0x04,
                'XBUTTON1':0x05,
                'XBUTTON2': 0x06,
                'BACKSPACE': 0x08,
                'TAB': 0x09,
                'CLEAR': 0x0C,
                'RETURN': 0x0D,
                'SHIFT': 0x10,
                'CONTROL': 0x11,
                'ALT': 0x12,
                'PAUSE': 0x13,
                'CAPS-LOCK': 0x14,
                'ESCAPE': 0x1B,
                'SPACEBAR': 0x20,
                'PAGE-UP': 0x21,
                'PAGE-DOWN': 0x22,
                'END': 0x23,
                'HOME': 0x24,
                'LEFT': 0x25,
                'UP': 0x26,
                'RIGHT': 0x27,
                'DOWN': 0x28,
                'PRINT-SCREEN': 0x2C,
                'PRINT': 0x29,
                'SELECT': 0x2A,
                'EXECUTE': 0x2B,
                'INSERT': 0x2D,
                'DELETE': 0x2E,
                'HELP': 0x2F,
                '0': 0x30,
                '1': 0x31,
                '2': 0x32,
                '3': 0x33,
                '4': 0x34,
                '5': 0x35,
                '6': 0x36,
                '7': 0x37,
                '8': 0x38,
                '9': 0x39,
                'A': 0X41,
                'B': 0X42,
                'C': 0X43,
                'D': 0X44,
                'E': 0X45,
                'F': 0X46,
                'G': 0X47,
                'H': 0X48,
                'I': 0X49,
                'J': 0X4A,
                'K': 0X4B,
                'L': 0X4C,
                'M': 0X4D,
                'N': 0X4E,
                'O': 0X4F,
                'P': 0X50,
                'Q': 0X51,
                'R': 0X52,
                'S': 0X53,
                'T': 0X54,
                'U': 0X55,
                'V': 0X56,
                'W': 0X57,
                'X': 0X58,
                'Y': 0X59,
                'Z': 0X5A,
                'LWIN': 0x5B,
                'RWIN': 0x5C,
                'SLEEP': 0x5F,
                'NUMPAD0': 0x60,
                'NUMPAD1': 0x61,
                'NUMPAD2': 0x62,
                'NUMPAD3': 0x63,
                'NUMPAD4': 0x64,
                'NUMPAD5': 0x65,
                'NUMPAD6': 0x66,
                'NUMPAD7': 0x67,
                'NUMPAD8': 0x68,
                'NUMPAD9': 0x69,
                'MULTIPLY': 0x6A,
                'ADD': 0x6B,
                'SEPARATOR': 0x6C,
                'SUBTRACT': 0x6D,
                'DECIMAL': 0x6E,
                'DIVIDE': 0x6F,
                'F1': 0x70,
                'F2': 0x71,
                'F3': 0x72,
                'F4': 0x73,
                'F5': 0x74,
                'F6': 0x75,
                'F7': 0x76,
                'F8': 0x77,
                'F9': 0x78,
                'F10': 0x79,
                'F11': 0x7A,
                'F12': 0x7B,
                'NUM-LOCK': 0x90,
                'SCROLL-LOCK': 0x91,
                'LSHIFT': 0xA0,
                'RSHIFT': 0xA1,
                'LCONTROL': 0xA2,
                'RCONTROL': 0xA3,
                'LALT': 0xA4,
                'RALT': 0xA5,
                'PLUS': 0xBB,
                'COMMA': 0xBC,
                'MINUS': 0xBD,
                'PERIOD': 0xBE,
                'OEM1': 0xBA,
                'OEM2': 0xBF,
                'OEM3': 0xC0,
                'OEM4': 0xDB,
                'OEM5': 0xDC,
                'OEM6': 0xDD,
                'OEM7': 0xDE,
                'MUTE': 0xAD,
                'VOLUME-DOWN': 0xAE,
                'VOLUME-UP': 0xAF,
                'NEXT-TRACK': 0xB0,
                'PREVIOUS-TRACK': 0xB1,
                'STOP': 0xB2,
                'PLAY/PAUSE': 0xB3
               }


def get_control_key_states():
    shift = user.get_key_state(VirtualKeys['SHIFT'])
    ctrl = user.get_key_state(VirtualKeys['CONTROL'])
    alt = user.get_key_state(VirtualKeys['ALT'])

    return shift, ctrl, alt
